name: ci

permissions:
  contents: read

on:
  - push
  - pull_request

jobs:
  ci:
    name: Run ci
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v5.1.0
      with:
        go-version: 1.23.1
    - run: go install 
    - run: go test ./...
    - run: go vet ./...
    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: latest
        install-go: false
