name: test

permissions:
  contents: read

on:
  - push
  - pull_request

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Checkout code
        uses: actions/checkout@v4

      - name: run tests
        run: |
          go mod tidy
          go test -v ./...
